apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cerberus-pokedex
spec:
  provider:
    cerberus:
      region: us-west-2
      sdb: pokedex
      cerberusURL: https://cerberus.my.domain
      auth:
        jwt:
          serviceAccountRef:
            name: test-cerberus-creds
            namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-cerberus-creds
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000111222333:role/cerberus-read-access
