apiVersion: v1
stringData:
  id: "0039"
  type: Fairy
immutable: false
kind: Secret
metadata:
  name: jigglypuff
type: Opaque

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: jigglypuff
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
  - name: cerberus-pokedex
    kind: ClusterSecretStore
  selector:
   secret:
      name: jigglypuff
  data:
  - match:
      secretKey: id # key in K8s secret
      remoteRef:
        property: id # property of the secret in Cerberus, MUST BE SET
        remoteKey: pokemons/jigglypuff # key of the secret in Cerberus
  - match:
      secretKey: type
      remoteRef:
        property: type
        remoteKey: pokemons/jigglypuff
