apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bulbazaur
spec:
  secretStoreRef:
    name: cerberus-pokedex
    kind: SecretStore
  refreshInterval: "1m"
  target:
    deletionPolicy: "Delete"
  data:
  - secretKey: pokemon-type # key in the secret, if not set the same as remoteRef.key
    remoteRef:
      key: cerberus-pokedex # path to secret in Cerberus
      property: type # property of the secret in Cerberus. If not set the whole secrets is published under the secretKey as JSON
  dataFrom:
  - extract: # extract returns all properties of the secret as keys in Kubernetes secret
      key: pokemons/jigglypuff
      version: b28afb82-b6e3-4c6e-b141-c54808edb632 # if set, the specific version will be retrieved
  - find: # find recursively searches for secrets in Cerberus matching the regexp.
      path: pokemons/ # start of the search
      name:
        regexp: ".*zaur.*"
